### ISSUE TITLE
When will you open source？

### ISSUE THREAD

**Issue by QinZiwen** [janinethoma/learning1M#1]
When will you open source？

**Comment by janinethoma** [comment]
Dear Ziwen Qin,

Thank you for your interest. I am currently still cleaning the code. I will upload it as soon as possible (maybe in one or two weeks).

Cheers,
Janine

________________________________
Von: Ziwen Qin <notifications@github.com>
Gesendet: Samstag, 29. August 2020 06:25
An: janinethoma/learning1M <learning1M@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [janinethoma/learning1M] When will you open source？ (#1)


When will you open source？

**Comment by Zumbalamambo** [comment]
1+
