### ISSUE TITLE
Confusion about model names

### ISSUE THREAD

**Issue by AlbertoJaenal** [janinethoma/learning1M#3]
Hi, @janinethoma 

thanks for sharing your code and your models! It will be quite useful for subsequent research.
However, I have some doubts about the names of the models in dropbox, and I am not quite sure about what CNN I need.

So, I've thought about sorting them into a table. I've sort somehow them, but I'm not sure if they are correct, so correct me if needed.

### **Geometrically mappable features**     
I guessed that every net with a __xy_000_ suffix belongs to this paper

| Name in paper | Model name |
| - | - |
| **Off-the-shelf VGG-16** | offtheshelf  |
| **Dist** | |
| **Huber dist** | |
| **Triplet** | triplet_xy_000 (NetVLAD) |
| **Quadruplet** | quadruplet_xy_000 |
| **Lazy triplet** | lazy_triplet_xy_000 |
| **Lazy quadruplet** | lazy_quadruplet_xy_000 |
| **Triplet + dist** | distance_triplet_xy_000 |
| **Lazy quat + dist** | |
| **Triplet + huber dist** | huber_distance_triplet_xy_000 |
| **Lazy quat + huber dist** | |

### **Learning 1M**     

Here some aclarations about the Large oxford ones and some unknown models

| Name in paper | Models |
| - | - |
| **I. COLD Triplet** | triplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **I. COLD Lazy triplet** | lazy_triplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **I. COLD Quadruplet** | quadruplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **I. COLD Lazy quadruplet** | lazy_quadruplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **I. COLD Triplet+distance** | sum_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **I. COLD Triplet+Huber distance** | h_sum_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **II. Small oxford Triplet** | triplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **II. Small oxford Lazy triplet** | lazy_triplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **II. Small oxford Quadruplet** | quadruplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **II. Small oxford Lazy quadruplet** | lazy_quadruplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **II. Small oxford Triplet+Huber distance*** | h_sum_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **III. Large oxford volume??** | ha0_loresidual_det_muTrue_renone_vl64_pca_eccv_000 |
| **III. Large oxford volume??** | ha0_loresidual_det_muTrue_renone_vl0_pca_eccv_001 |
| **IV. Pittsburgh Triplet** | Pittsburg |
| **V. ImageNet Off-the-shelf** | offtheshelf |
| **Unknown** | evil_quadruplet_hp_001 |
| **Unknown** | evil_triplet_hp_001 |
| **Unknown** | residual_det_0.0_eccv_000 |
| **Unknown** | residual_det_512_none_0_fc_eccv_000 |

Thanks for everything.
Regards

**Comment by janinethoma** [comment]
Dear @AlbertoJaenal, 
Thank you for your interest in my research. Here are the complete lists from the names in the papers to the model names:
 
#### Models used in *Learning Condition Invariant Features for Retrieval-BasedLocalization from 1M Images* Table 2
| Name | Model |
|-|-|
| I: Triplet | triplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| I: Quadruplet | quadruplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| I: Lazy triplet | lazy_triplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| I: Lazy quadruplet | lazy_quadruplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| I: Triplet + distance | sum_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| I: Triplet + Huber dist. | h_sum_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| II: Triplet | triplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| II: Quadruplet | quadruplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| II: Lazy triplet | lazy_triplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| II: Lazy quadruplet | lazy_quadruplet_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| II: Triplet + Huber dist.~ | h_sum_5e-6_full-10-25_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| III: Triplet | triplet_xy_000 |
| III: Quadruplet | quadruplet_xy_000 |
| III: Lazy triplet | lazy_triplet_xy_000 |
| III: Lazy quadruplet | lazy_quadruplet_xy_000 |
| III: Triplet + distance | distance_triplet_xy_000 |
| III: Triplet + Huber dist. | huber_distance_triplet_xy_000 |
| **III: Triplet + HP** | evil_triplet_hp_001 |
| **III: Quadruplet + HP** | evil_quadruplet_hp_001 |
| **III: Volume without HP** | ha0_loresidual_det_muTrue_renone_vl64_pca_eccv_000 |
| **III: Volume* without HP** | ha0_loresidual_det_muTrue_renone_vl0_pca_eccv_001 |
| **III: Volume** | residual_det_0.0_eccv_000 |
| **III: Volume*** | residual_det_512_none_0_fc_eccv_000 |
| IV: Triplet | pittsnetvlad |
| V: Off-the-shelf | offtheshelf |

#### Models used in *Geometrically Mappable Image Features* Figure 3
|Name| Oxford Model|
|-|-|
| Off-the-shelf | offtheshelf |
| **Triplet + dist.** | distance_triplet_xy_000 |
| **Triplet + Huber dist.** | huber_distance_triplet_xy_000 |
| **Lazy quad. + dist.** | distance_lazy_quadruplet_xy_000 |
| **Lazy quad. + Huber dist.** | huber_distance_lazy_quadruplet_xy_000 |
| Dist. | distance_xy_000 |
| Huber | huber_distance_xy_000 |
| Triplet | triplet_xy_000 |
| Quadruplet | quadruplet_xy_000 |
| Lazy triplet | lazy_triplet_xy_000 |
| Lazy quadruplet | lazy_quadruplet_xy_000 |

|Name| COLD Model
|-|-|
| Off-the-shelf | offtheshelf |
| **Triplet + dist.** | sum_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **Triplet + Huber dist.** | h_sum_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **Lazy quad. + dist.** | nlq_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| **Lazy quad. + Huber dist.** | hlq_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| Dist. | simple_dist_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| Huber | huber_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| Triplet | triplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| Quadruplet | quadruplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| Lazy triplet | lazy_triplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |
| Lazy quadruplet | lazy_quadruplet_5e-6_all_conditions_angle_1-4_cu_LRD0.9-5_noPCA_lam0.5_me0 |

Some of the models from *Geometrically Mappable Image Features* were not on Dropbox yet. I will add them now.
